version: '3.8'

services: # defines container or service to be run
  backend: # name of the backend service
    container_name: ai_web_builder-backend
    image: ai_web_builder-backend-image
    build: # build docker image using files inside the backend/ directory
      context: ./backend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL=${MODEL}

  frontend:
    container_name: ai_web_builder-frontend
    image: ai_web_builder-frontend-image
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE=https://gauravkeshri.dev:api # this is the base url for the backend api,
        # we will use this in frontend to make api calls to the backend
  nginx:
    image: nginx:latest
    container_name: ai_web_builder-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend