events {}

http {
    server {
        listen 80;
        server_name aiwebbuilder.gauravkeshri.dev; # Locks Nginx to this exact URL
        # Route API requests to the Python backend
        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://backend:8000;
        }

        # Route everything else to the frontend UI
        location / {
            proxy_pass http://frontend:8080;
        }
    }
}